"""Estrutura inicial da base de dados

Revision ID: 7a6e7c1ed4e3
Revises: 
Create Date: 2026-04-11 12:33:24.821869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6e7c1ed4e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('senha', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('cliente',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('previous_purchases', sa.Float(), nullable=True),
    sa.Column('cart_items', sa.Float(), nullable=True),
    sa.Column('discount_seen', sa.Float(), nullable=True),
    sa.Column('ad_clicked', sa.Float(), nullable=True),
    sa.Column('returning_user', sa.Float(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['usuario_responsavel'], ['usuarios.cpf'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
